### PR TITLE
Feature/capitalize candidate name dashboard

### PR DESCRIPTION
**Pull request by ahanif19**

### CODE REVIEW

**Comment by ahanif19** [comment]
It capitalizes your name in the dashboard (example below)

image

If we don't have it, the 'A' in 'Abdullah' would be lower case. Looks like we fixed this in the employer dashboard but not the candidate dashboard

**Comment by jackxujh** [comment]
Is the name the same as the user typed in the candidate profile?

**Comment by ahanif19** [comment]
Yes, if you look in the dashboard view at line 116:

`candidate_name = candidate.candidate_profile.first_name`

**Comment by jackxujh** [comment]
Okay, I see. I was just not sure if there were some people whose names are lower cased.

**Pull request closed without merging**
